name: 🧮 Metrics

on:
  workflow_dispatch:        # позволяет запускать вручную
  push:                     # пересчитается при каждом пуше
    branches: [ "main" ]
  schedule:
    - cron: '0 3 * * *'     # ежедневно 03:00 UTC

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: profile-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity
          plugin_activity: yes
          plugin_activity_limit: 1 year
          config_timezone: Europe/Moscow
