name: 🧮 Metrics

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 3 * * *'

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/assets/metrics/profile-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity
          plugin_activity: yes
          plugin_activity_limit: 1 year
          plugin_activity_visibility: all
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_visibility: all
          plugin_languages_criteria: lines
          plugin_languages_indepth: yes
          plugin_languages_ignored: markdown, json, yaml
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: Europe/Moscow